# Generated by Django 6.0.5 on 2026-06-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo')),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Venda')),
                ('estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
    ]
