# Generated by Django 6.0.5 on 2026-06-12 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_estoque_movimentacaoestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='estoque_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='estoque_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
