# Generated by Django 6.0.5 on 2026-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cadastro', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('FUNCIONARIO', 'Funcionário')], max_length=20)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
