# Generated by Django 6.0.5 on 2026-06-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerguntaFrequentes',
            new_name='PerguntaFrequente',
        ),
    ]
